apiVersion: v1
kind: Service
metadata:
  name: nvindex-discovery
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
spec:
  ports:
  - name: discovery
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
  type: ClusterIP

