apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-viewer"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: viewer
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
        app.kubernetes.io/component: viewer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
        app.kubernetes.io/component: viewer
    spec:
      volumes:
        - name: viewer-files
          emptyDir: {}
        {{ if .Values.useNginx }}
        - name: nginx-conf-vol
          configMap:
            name: nginx-conf
        {{ end }}
        {{ if .Values.tls.base64EncodedPrivateKey }}
        - name: tls-certs-files
          secret:
            secretName: "{{ .Release.Name }}-tls"
        {{ end }}
        - name: htpasswd-file
          emptyDir: {}
        - name: rsync-scene-files
          emptyDir: {}
        - name: nvindex-conf-vol
          configMap:
            name: nvindex-conf
      initContainers:
          # Copy viewer files from IndeX container into a emptyDir that will
          # be used by the nginx container.
        {{ if .Values.useNginx }}
        - name: copy-viewer-files
          image: "{{ .Values.imageNvindex }}"
          command: ['bash']
          args: ['-c', 'cp -R /opt/nvidia-index/demo/html5_viewer/* /output']
          volumeMounts:
            - name: viewer-files
              mountPath: /output
        {{ if .Values.viewerGeneratedPassword }}
          # Generate a htpasswd file for basic auth based on generate password for nginx.
        - name: gen-htpasswd
          image: "{{ .Values.imageNvindex }}"
          command: ['bash']
          # Generated passwd needs to be decoded from base64, encrypted and saved.
          args: ['-c', 'echo {{ .Values.viewerGeneratedPassword }} | echo nvindex:$(openssl passwd -apr1 -in -) > /htpasswd/htpasswd']
          volumeMounts:
            - name: htpasswd-file
              mountPath: /htpasswd
        {{ end }} # if passwd enabled
        {{ end }} # if nginx enabled
          # Sync (non-data) files from given dataLocation.
        - name: rsync-scene-files
          image: google/cloud-sdk:alpine
          volumeMounts:
            - name: rsync-scene-files
              mountPath: /scenes
          command: ['bash']
          args: ['-c', 'gsutil -m rsync -d -r -x ".*\/data\/*.*$" {{ .Values.dataLocation }} /scenes']
      containers:
        - name: nvindex-tape
          image: "{{ .Values.imageNvindex }}"
          command: [ './nvindex-viewer.sh' ]
          args: [
            '--nogl',
            '--reference-viewer',
            '--components',
            '-dice::network::mode', 'TCP_WITH_DISCOVERY',
            '-dice::network::retention', '30',
            '-app::enable_fail_safety', 'yes',
            '-dice::network::discovery_address', '0.0.0.0:$(NVINDEX_DISCOVERY_SERVICE_PORT)',
            '--add', "/config/extra.prj"
          ]
          env:
            - name: NVINDEX_DATA
              value: "{{ .Values.dataLocation }}"
          ports:
          - containerPort: 5555
          - containerPort: 10000
          - containerPort: 10001
          - containerPort: 3333
          - containerPort: 4444
          volumeMounts:
          - name: rsync-scene-files
            mountPath: /scenes
          - name: nvindex-conf-vol
            mountPath: /config
          resources:
            limits:
              nvidia.com/gpu: "{{ .Values.gpuCount }}"
        {{ if .Values.useNginx }}
        - name: nginx
          image: nginx
          volumeMounts:
          - name: viewer-files
            mountPath: /usr/share/nginx/html
          - name: nginx-conf-vol
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          {{ if .Values.tls.base64EncodedPrivateKey }}
          - name: tls-certs-files
            mountPath: /root/certs
          {{ end }}
          {{ if .Values.viewerGeneratedPassword }}
          - name: htpasswd-file
            mountPath: /htpasswd
          {{ end }}
          ports:
          - containerPort: 80
          - containerPort: 443
        {{ end }}
