application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  deployerImage:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  imageNvindex:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nodeCount:
    title: Number of nodes to span.
    type: integer
    default: 1
  gpuCount:
    title: Number of NVIDIA GPUs per node (must exist in cluster).
    type: integer
    default: 1
  viewerGeneratedPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  genCertificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate
  dataLocation:
    type: string
    title: Bucket where data is stored. Read documentation on format.
    default: gs://nvindex-data-samples/scenes
required:
- name
- namespace
- deployerImage
- imageNvindex
- nodeCount
- gpuCount
- viewerGeneratedPassword
- genCertificate
- dataLocation
form:
- widget: help
  description: My arbitrary <i>description</i>
x-google-marketplace:
  clusterConstraints:
    resources:
    - affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
